import spot
import buddy
import argparse
import subprocess
import glob
from dataclasses import dataclass
from pathlib import Path
from typing import List, Dict, Set, Tuple

# The controller #
##################

@dataclass
class csg:
    """
    The controller class.

    Attributes:
        twa: The automaton.
        states_bdds: The BDDs of the states.
        edges_concsets: The concurrent sets of the edges.
        outputs: The output APs.
        current_state: The current state of the controller, always initialized at 0.
    """
    twa: spot.twa_graph
    states_bdds: Dict[int,buddy.bdd]
    edges_concsets: Dict[int, Dict[str, int]]
    outputs: Set[int]

    current_state = 0
    
    def step(self, inputs_val: Dict[int, bool]):
        """
        Makes one transition of the controller: it changes the inner state of the controller following a transition.

        Args:
            inputs_val: A valuation of AP where the values of input APs are taken for the transition of the controller.

        Returns:
            A valuation of AP where the values of outputs APs are generated by the transition.
        """
        direction_step = self.get_a_paretto_max_edge(inputs_val)
        if direction_step is not None:
            self.current_state = direction_step[1]
            return direction_step[0]
        return compute_outputs(self.states_bdds[self.current_state], self.outputs)
    # ici on va devoir reecrire la fonction step qui permet de passer dun etat a un autre grace aux transitions
    #il faut faire attention lorsquon a les inputs qui ne sont plus valides et quon va devoir terminer des transitions
    # quelle transition se finit, pour ca on reprend get_a_paretto_max_edge qui sert a choisir la prochaine cellule / la transition a terminer
    def get_a_paretto_max_edge(self, inputs_val: Dict[int, bool]):
        """
        Choose an edge coherent with inputs and that is maximal, i.e. there is not another edge coherent with the input
        that corresponds to a bigger multiset of transition.

        Args:
            inputs_val: A valuation of AP where the values of input APs are taken for the transition of the controller.

        Returns:
            The output generated by the edge and the destination state.
        """
        resu_edge = None
        for edge in self.twa.out(self.current_state):
            if satisfies_bdd(inputs_val, edge.cond, self.outputs) and (resu_edge is None or leq_mset(self.edges_concsets[self.twa.edge_number(resu_edge)], self.edges_concsets[self.twa.edge_number(edge)])):
                resu_edge = edge
        if resu_edge is not None:
            return (compute_outputs(resu_edge.cond, self.outputs), resu_edge.dst)

def satisfies_bdd (valuation: Dict[int, bool], bdd: buddy.bdd, outputs_set: Set[int]):
    """
    Args:
        valuation: A valuation of the AP.
        bdd: A BDD.
        outputs_list: Outputs APs.

    Returns:
        A Boolean indicating whether the valuation satisfies the input part of the bdd.
    """
    if bdd == buddy.bddfalse:
        return False
    if bdd == buddy.bddtrue:
        return True
    top = buddy.bdd_var(bdd)
    low = buddy.bdd_low(bdd)
    high = buddy.bdd_high(bdd)
    if top in outputs_set:
        return satisfies_bdd(valuation, low, outputs_set) or satisfies_bdd(valuation, high, outputs_set)
    if valuation[top]:
        return satisfies_bdd(valuation, high, outputs_set)
    else:
        return satisfies_bdd(valuation, low, outputs_set)

def compute_outputs(bdd: buddy.bdd, outputs: set[int]):
    """
    Extract a compatible valuation for the output APs from the given cube
    over input and output APs. 
    Args:
        bdd: Input cube.
        outputs: bdd_vars of output APs as a set.

    Returns:
        The valuation of output APs according to the bdd.
    """
    resu = {ap: False for ap in outputs}
    bdd_temp = bdd
    while bdd_temp != buddy.bddtrue:
        top = buddy.bdd_var(bdd_temp)
        low = buddy.bdd_low(bdd_temp)
        high = buddy.bdd_high(bdd_temp)
        if low == buddy.bddfalse:
            if top in outputs:
                resu[top] = True
            bdd_temp = high
            continue
        if high == buddy.bddfalse:
            if top in outputs:
                resu[top] = False
            bdd_temp = low
            continue
        raise Exception("Not a cube!")
    return resu

# Important classes #
#####################

@dataclass
class pnTransition:
    """
    A transition in a Petri net.

    Attributes:
        pre: The pre-places.
        post: The post-places.
    """
    pre: List[int]
    post: List[int]

@dataclass
class petrinet:
    """
    A Petri net.

    Attributes:
        initial: The initial marking.
        map: Maps transition id (int) to their names.
        transitions: The transitions of the Petri net.
    """
    initial: Tuple[int]
    map: Dict[int, str]
    transitions: Dict[int, pnTransition]

@dataclass
class ipnTransition:
    """
    A transition in an interpreted Petri net.

    Attributes:
        pre: The pre-places.
        post: The post-places.
        inputs: The inputs of the transition.
        outputs: The outputs of the transition.
    """
    pre: List[int]
    post: List[int]
    inputs: str
    outputs: str

@dataclass
class ipetrinet:
    """
    An interpreted Petri net.

    Attributes:
        initial: The initial marking.
        map: The map of the Petri net.
        inputs: The inputs of the Petri net.
        outputs: The outputs of the Petri net.
        placesOuts: The outputs of the places.
        transitions: The transitions of the Petri net.
    """
    initial: tuple
    map: dict
    inputs: list
    outputs: list
    placesOuts: dict
    transitions: dict

@dataclass
class maxCell:
    """
    A cell in a MaxCell HDA.

    Attributes:
        marking: The marking of the cell.
        concset: The concurrent set of the cell.
        transitions: The transitions of the cell.
    """
    marking: tuple
    concset: dict
    transitions: dict

@dataclass
class hdaTransition:
    """
    A transition in a MaxCell HDA.

    Attributes:
        unstrat: The unstarted transitions.
        terminate: The terminated transitions.
        continued: The continued transitions.
        start: The started transitions.
    """
    unstrat: dict
    terminate: dict
    continued: dict
    start: dict

# Parsing of input #
####################

def parse_petri_net(pn_text: str):
    """
    Builds the Petri net specified in pn_text.

    Args:
        pn_text: The text of the Petri net.

    Returns:
        The Petri net.
    """
    Map = dict()
    Transitions = dict()

    lines = pn_text.replace(' ','').split("\n")

    i=0
    while lines[i] != "<Transitions>":
        i += 1
    i0 = i +1
    while lines[i] != "</Transitions>":
        i += 1
    init_marking = tuple([int(m) for m in ((lines[i0-2]).split(":")[1][1:-1]).split(',')]) # psc You could do a eval
    for transition_text in lines[i0:i]:
        parts = transition_text.split(":") # psc you could use a re.match
        name_texts = parts[0].split(",")
        id = int(name_texts[0][1:])
        name = name_texts[1][1:-2]
        Map[id] = name

        defs_places = parts[1].split("],[")
        preplaces = [int(i) for i in defs_places[0][1:].split(",")]
        postplaces = [int(i) for i in defs_places[1][:-1].split(",")]
        Transitions[name] = pnTransition(preplaces, postplaces)
    return petrinet(init_marking, Map, Transitions)

def parse_io (pn: petrinet, io_text: str):
    """
    Builds the interpreted Petri net with base Petri net pn and where the inputs/outputs specifications is given by io_text.

    Args:
        pn: The base Petri net.
        io_text: The text of the interpreted Petri net.

    Returns:
        The interpreted Petri net.
    """
    lines = io_text.replace(' ', '').split("\n")

    inputs_list = lines[0].split(":")[1][1:-1].split(",")
    outputs_list = lines[1].split(":")[1][1:-1].split(",")
    
    Transitions = dict()

    i=0
    while lines[i] != "<Transitions>":
        i += 1
    i0 = i +1
    while lines[i] != "</Transitions>":
        i += 1
    
    transitions_text = lines[i0:i]
    for transition_text in transitions_text:
        parts = transition_text.split(":")
        name_texts = parts[0].split(",")
        name = name_texts[1][1:-2]
        defs_io = parts[1][1:-1].split(";")
        inputs = defs_io[0]
        outputs = defs_io[1]
        Transitions[name] = ipnTransition(pn.transitions[name].pre,pn.transitions[name].post, inputs, outputs)
    
    placeOuts = dict()
    while lines[i] != "<Place-Output>":
        i += 1
    i0 = i +1
    while lines[i] != "</Place-Output>":
        i += 1
    if i > i0 +1:
        place_out_text = lines[i0:i]
        for placeio_text in place_out_text:
            placeio = placeio_text.split(':')
            outputs = placeio[1][1:-1]
            placeOuts[int(placeio[0])] = outputs
    return ipetrinet(pn.initial, pn.map, inputs_list, outputs_list, placeOuts, Transitions)

def add_transitions(transi_list: List[pnTransition], pn: ipetrinet, transitions: Dict[str,int]):
    """
    Adds all the transitions in transi_list, given by there id, to the concset transitions, addressed by name.

    Args:
        transi_list: The list of transitions to add.
        pn: The Petri net.
        transitions: The concset.
    """
    for a in transi_list:
        if a != '':
            transition = pn.map[int(a)]
            if transition in transitions.keys():
                transitions[transition] += 1
            else:
                transitions[transition] = 1

# 
def parse_maxcell_hda(hda_text: str, pn: ipetrinet):
    """
    Builds the MaxCell HDA given by hda_text and representing pn
    
    Args:
        hda_text: The text for the hda.
        pn: The bas Petri net.
    
    Returns:
        The hda.
    """
    lines = hda_text.replace(' ','').split("\n")
    Cells = dict()
    i_start = 0
    while i_start<len(lines) and lines[i_start] != "":
        id = lines[i_start].split(":")
        name = int(id[0])
        markconc = id[1].split("]x[")
        marking = tuple([int(i) for i in markconc[0][1:].split(",")])
        concset = dict()
        for a in markconc[1][:-1].split(","):
            if a != "":
                if a in concset.keys():
                    concset[a] += 1
                else:
                    concset[a] = 1
        Transitions = dict()
        i_end = i_start+2
        while i_end < len(lines) and ":" not in lines[i_end] and lines[i_end] != "":
            i_end += 1
        transitions = lines[i_start+2:i_end-1]
        if transitions != []:
            for transition_text in transitions:
                transition_parts = transition_text.split(";")
                maxcell_target = int(transition_parts[3])
                if maxcell_target not in Transitions.keys():
                    Transitions[maxcell_target] = []
                unst_term = transition_parts[1].split("|")

                transition = dict()
                unstart = dict()
                unstart_list = unst_term[0][1:-1].split(",")
                add_transitions(unstart_list, pn, unstart)
                continued = dict()
                continued_list = unst_term[0][1:-1].split(",")
                add_transitions(continued_list, pn, continued)
                terminate = dict()
                terminate_list = unst_term[1][1:-1].split(",")
                add_transitions(terminate_list, pn, terminate)
                start = dict() 
                start_list = transition_parts[2].split("|")[1][1:-1].split(",")
                add_transitions(start_list, pn, start)
                Transitions[maxcell_target].append(transition)
        Cells[name] = maxCell(marking, concset, Transitions)
        i_start = i_end
    return Cells

# Computing concurrent step graph #
###################################

# MultiSet operations #
# ------------------- #

def diff_mset(mset1: Dict[int,int], mset2: Dict[int,int]):
    """
    Compute the difference mset1 - mset2.
    
    Args:
        mset1: The smaller multiset.
        mset2: The bigger multiset.
    
    Returns:
        The difference multiset.
    """
    resu = dict()
    for key in mset1.keys() & mset2.keys():
        value = mset1[key] - mset2[key]
        if value > 0:
            resu[key] = value
    for key in set(mset1.keys()).difference(mset2.keys()):
        resu[key] = mset1[key]
    return resu

def leq_mset(mset1: Dict[int,int], mset2: Dict[int,int]):
    """
    Predicate whether mset1 <= mset2.
    
    Args:
        mset1: The multiset that is checked to be smaller.
        mset2: The multiset that is checked to be bigger.
    
    Returns:
        The Boolean whether mset1 <= mset2.
    """
    return not any(key not in mset2.keys() or mset1[key] > mset2[key] for key in mset1.keys())
 
def sub_multi_set(mset: Dict[int,int]):
    """
    Generate all sub-multisets of mset.
    
    Args:
        mset: The multiset.

    Returns:
        The generator of the submultisets of mset.
    """
    return sub_multi_set_run(mset, set(mset.keys()))

def sub_multi_set_run(mset: Dict[int,int], keys: Set[int]):
    """
    The internal function of sub_multi_set. Computes all the submultisets of mset on the keys keys.
    
    Args:
        mset: The multiset.
        keys: The keys.
    
    Returns:
        The generator of the submultisets on keys.
    """
    if len(keys) == 0:
        yield dict()
    else:
        key = keys.pop()
        for sub_mset in sub_multi_set_run(mset, keys):
            for i in range(mset[key]+1):
                if i != 0:
                    sub_mset[key] = i
                elif key in sub_mset.keys():
                    del sub_mset[key]
                yield sub_mset.copy()
        keys.add(key)

# Operations on markings of the Petri-net #
# --------------------------------------- #

def compute_marking_pre(marking: Tuple[int], concset: Dict[int,int], pn: ipetrinet):
    """
    Compute the new marking obtained after unstarting all transitions in concset from marking in pn.
    
    Args:
        marking: The initial marking.
        concset: The multiset of transitions to unstart.
        pn: The ambiant Petri net.
    
    Returns:
        The obtained marking.
    """
    new_marking = [0]*len(marking)
    for place in range(len(marking)):
        mplace = marking[place]
        for transition in concset.keys():
            if place in pn.transitions[transition].pre:
                mplace += concset[transition]
        new_marking[place] += mplace
    return tuple(new_marking)

def compute_marking_transi(marking: Tuple[int], concset: Dict[int,int], pn: ipetrinet):
    """
    Compute the new marking obtained after firing and terminating all transitions in concset from marking in pn.
    
    Args:
        marking: The initial marking.
        concset: The multiset of transitions to fire.
        pn: The ambiant Petri net.
    
    Returns:
        The obtained marking.
    """
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for transition in concset.keys():
            if place in pn.transitions[transition].pre:
                mplace -= concset[transition]
                if mplace < 0:
                    raise Exception("transition with not enough tokens")
            if place in pn.transitions[transition].post:
                mplace += concset[transition]
        new_marking = new_marking + (mplace,)
    return new_marking

def compute_marking_maxcell_transi(marking: Tuple[int], transitions: hdaTransition, pn: ipetrinet):
    """
    Compute the new marking obtained after applying the MaxCell transitions (in the MaxCell HDA).
    
    Args:
        marking: The initial marking.
        transitions: The transition in the MaxCell HDA.
        pn: The ambiant Petri net.
        
    Returns:
        The obtained marking.
    """
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for unstart in transitions.unstart.keys():
            if place in pn.transitions[unstart].pre:
                mplace += transitions.unstart[unstart]
        for terminate in transitions.terminate.keys():
            if place in pn.transitions[terminate].post:
                mplace += transitions.terminate[terminate]
        for start in transitions.start.keys():
            if place in pn.transitions[start].pre:
                mplace -= transitions.start[start]
                if mplace < 0:
                    raise Exception("transition with not enough tokens")
        new_marking = new_marking + (mplace,)
    return new_marking

# Logcal operations #
# ----------------- #

def get_literal(strg: str, ap: Dict[str, buddy.bdd]):
    """
    Get the ap of a literal.
    
    Args:
        strg: The string of the litteral.
        ap: The map from strings of atomic propositions to their buddy representation.
    
    Returns:
        The bdd of the litteral.
    """
    if strg[0] == "!":
        return buddy.bdd_not(ap[strg[1:]])
    else:
        return ap[strg]

def get_string_bdd(strg: str, ap: Dict[str, buddy.bdd]):
    """
    Builds a bdd for the string strg representing a formula in conjunctive normal form over APs ap.
    
    Args:
        strg: The text of the formula.
        ap: The map from strings of atomic propositions to their buddy representation.
    
    Returns:
        The bdd of the formula.
    """
    clauses = strg.replace(" ","").split('&')
    resu = buddy.bddtrue
    for clause in clauses:
        literals = clause.split('|')
        resu_clause = buddy.bddfalse
        for literal in literals:
            resu_clause = resu_clause | get_literal(literal, ap)
        resu = resu & resu_clause
    return resu

def get_marking_output(marking: Tuple[int], pn: ipetrinet, ap: Dict[str, buddy.bdd]):
    """
    Builds the bdd for the output of a marking.
    
    Args:
        marking: The marking.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
    
    Retruns:
        The bdd for the output of the marking."""
    resu = buddy.bddtrue
    for state in range(len(marking)):
        try:
            if marking[state] > 0:
                resu = resu & get_string_bdd(pn.placesOuts[state], ap) # psc normally try except should be faster
        except Exception:
            continue
    return resu

    #ce quon veut rajouter cest separer les bdds outputs/inputs
    # pour ca on peut faire un double/tuple jsplus de dictionnaire pour les inputs et les outputs, 
    # cest ce quon renverra
def get_cell_output(cell: maxCell, pn: ipetrinet, ap: dict):
    """
    Builds the bdd for the active inputs / outputs of a MaxCell.
    
    Args:
        cell: The MaxCell in the HDA.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
    
    Returns:
        The bdds for the inputs and outputs of the cell.
    """

    resu = buddy.bddtrue
    #on parcourt les outputs des transitions en cours dans cette cellule
    for transition in cell.concset.keys():
        t = pn.transitions[transition]
        #si la transition a des inputs, on rajoute dans les inputs
        if t.inputs:
            resu = resu & get_string_bdd(t.inputs, ap)
        #si la transition a des outputs, on rajoute dans les outputs
        if t.outputs:
            resu = resu & get_string_bdd(t.outputs, ap)
    # on parcourt les places pour regarder le marking 
    for place in range(len(cell.marking)):
        tokens = cell.marking[place]
        # si la place est marquee et definie des outputs on rajoute aussi
        if tokens > 0 and place in pn.placesOuts:
            resu = resu & get_string_bdd(pn.placesOuts[place], ap)
    return resu

def get_edge_output(pn_transitions: dict, pn: ipetrinet, ap: dict, cell: maxCell):
    """
    Builds the bdd for the inputs and outputs of an edge.
    
    Args:
        pn_transitions: The multiset of Petri net transitions starting or terminating on the edge.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
        cell: The MaxCell of the edge.
    
    Returns:
        The bdd for the inputs and outputs of the edge.
    """
    # on part des outputs de la cellule de depart
    # on separe les inputs dans un dictionnaire et les outputs de lautre
    resu = get_cell_output(cell, pn, ap)
    #on parcourt les transitions du pn actifs
    for trans in pn_transitions.keys():
        t = pn.transitions[trans]
        #on rajoute les conditions des inputs sil y en a
        if t.inputs:
            bdd_in = get_string_bdd(t.inputs, ap)
            resu = resu & bdd_in
            # on verifie que l ap reste possible sinon erreur
            if resu == buddy.bddfalse:
                raise Inputs_Error
        #on rajoute les outputs sil y en a aussi
        if t.outputs:
            bdd_out = get_string_bdd(t.outputs, ap)
            resu = resu & bdd_out
    return resu

def get_state(marking: Tuple[int], states: Dict[int, Tuple[int]], graph: spot.twa_graph, pn: ipetrinet, ap: Dict[str, buddy.bdd], states_bdds: Dict[int, buddy.bdd]):
    """
    The state of the marking. Builds a new state in the automaton, if necessary.

    Args:
        marking : The marking for the state.
        states: The dictionnary of already existing states.
        graph: The automaton.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
        states_bdd: The map from states to their output bdd.
    
    Returns:
        The state of the marking.
    """
    if marking in states:
        state = states[marking]
    else:
        label = get_marking_output(marking, pn, ap)
        state = graph.new_state()
        states[marking] = state
        states_bdds[state] = label
    return state

def get_state_for_cell(cell_id: int, cell: maxCell, cell_to_state, graph: spot.twa_graph, pn: ipetrinet, ap: Dict[str, buddy.bdd], states_bdds: Dict[int, buddy.bdd]):
    """
    The state of the cell. Builds a new state in the automaton, if necessary

    Args:
        cell_id: The id of the cell
        cell: The cell in the MaxCell HDA
        cell_to_state: The dictionnary of already existing states, mapped by cell id.
        graph: The automaton in construction.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
        states_bdd: The map from states to their output bdd.

    Returns:
        The state of the cell.
    """
    #on verifie si on a pas deja un etat cree pour la cellule
    if cell_id in cell_to_state:
        return cell_to_state[cell_id]
    #on calcule le bdd representant les outputs actifs de la cellule
    bdds = get_cell_output(cell, pn, ap)
    #on cree un nouvel etat au graphe quon enregistre dans notre dictionnaire pour la cellule
    state = graph.new_state()
    #on note dans cell_to_state que l etat associe a la cellule est celle ci
    cell_to_state[cell_id] = state
    #on note les outputs 
    states_bdds[state] = bdds
    return state

class Inputs_Error (Exception):
    """
    If a bdd for the inputs of a transition is false, the transition is not added to the automaton.
    """
    pass

class Outputs_Error (Exception):
    """
    If a bdd for the outputs is false, then, this error is raised.
    """
    def __init__(self, message):            
        super().__init__(message)

def get_io(marking_source: Tuple[int], concset: Dict[int,int], pn: ipetrinet, ap: Dict[str, buddy.bdd]):
    """
    Gets the input/output bdd when firing concset from marking_source.

    Args:
        marking_source: The initial marking.
        concset: The multiset of transitions.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
    
    Returns:
        The bdd for the input/outputs of firing concset from marking_source.
    """
    resu = get_marking_output(marking_source, pn, ap)
    for t in concset.keys():
        inputs = pn.transitions[t].inputs
        outputs = pn.transitions[t].outputs
        if inputs:
            bdd_inputs = get_string_bdd(inputs, ap)
            resu = resu & bdd_inputs
            if resu == buddy.bddfalse:
                raise Inputs_Error
        if outputs:
            bdd_outputs = get_string_bdd(outputs, ap)
            resu = resu & bdd_outputs
            if resu == buddy.bddfalse:
                raise Outputs_Error(f"Incompatible outputs in {marking_source} when firing {concset}")
            resu = resu & get_string_bdd(outputs, ap)
    return resu

def add_transition(graph:spot.twa_graph, 
                   pn: ipetrinet, 
                   ap: Dict[str, buddy.bdd], 
                   states_bdds: Dict[int, buddy.bdd], 
                   edges_ios: Dict[Tuple[Tuple[int]], buddy.bdd], 
                   edges_concsets: Dict[int, Dict[int, int]], 
                   marking_source: Tuple[int], 
                   concset: Dict[int,int], 
                   states: Dict[int, Tuple[int]]):
    """
    Adds a transition in the automaton from the state representing marking_source and following concset. Returns the obtained marking.
    
    Args:
        graph: The automaton in construction.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
        states_bdd: The map from states to their output bdd.
        edges_ios: The map from pair of markings to their list of possible input/output bdd.
        edges_concsets: The map from edges of the automaton to their multiset of transitions.
        marking_source: The initial marking.
        concset: The multiset of transitions.
        states: The map from markings to already existing states.
    
    Returns:
        The marking obtained after firing concset.
    """
    marking_target = compute_marking_transi(marking_source, concset, pn)
    state_source = get_state(marking_source, states, graph, pn, ap, states_bdds)
    state_target = get_state(marking_target, states, graph, pn, ap, states_bdds)
    try:
        label = get_io(marking_source, concset, pn, ap)
    except Inputs_Error:
        return marking_target
    if not (marking_source, marking_target) in edges_ios.keys():
        edge = graph.new_edge(state_source, state_target, label)
        edges_concsets[edge] = concset
        edges_ios[(marking_source, marking_target)] = [label]
    elif not any(existing_label == label for existing_label in edges_ios[(marking_source, marking_target)]):
        edge = graph.new_edge(state_source, state_target, label)
        edges_concsets[graph.edge_number(edge)] = concset
        edges_ios[(marking_source, marking_target)].append(label)
    return marking_target

def add_many_transitions(graph:spot.twa_graph, 
                         pn: ipetrinet, 
                         ap: Dict[str, buddy.bdd], 
                         states_bdds: Dict[int, buddy.bdd], 
                         edges_ios: Dict[Tuple[Tuple[int]], buddy.bdd], 
                         edges_concsets: Dict[int, Dict[int, int]], 
                         marking_source: Tuple[int], 
                         concset: Dict[int,int], 
                         states: Dict[int, Tuple[int]]):
    """
    Adds all the transitions from marking_source in the current cell with concset {concset}.

    Args:
        graph: The automaton in construction.
        pn: The ambiant Petri net.
        ap: The map from strings of atomic propositions to their buddy representation.
        states_bdd: The map from states to their output bdd.
        edges_ios: The map from pair of markings to their list of possible input/output bdd.
        edges_concsets: The map from edges of the automaton to their multiset of transitions.
        marking_source: The initial marking.
        concset: The multiset of transitions.
        states: The map from markings to already existing states.
    """
    for mset in sub_multi_set(concset):
        if len(mset) != 0:
            marking_target = add_transition(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking_source, mset, states)
            concset_comp = diff_mset(concset, mset)
            add_many_transitions(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking_target, concset_comp, states)

def hdatocsg (hda: Dict[int, maxCell], pn: ipetrinet):
    """
    Takes an HDA in MAXCELL form that represents the petri net pn in inputs and produces its controller graph associated
    
    Args:
        hda: The HDA.
        pn: The interpreted Petri net.
    
    Returns:
        The Controller Graph semantics of the HDA.
    """
    bdict = spot.make_bdd_dict()
    graph = spot.make_twa_graph(bdict)

    ap = dict()
    for ap_in in pn.inputs:
        ap_var = buddy.bdd_ithvar(graph.register_ap(ap_in))
        ap[ap_in] = ap_var
    
    outputs = set()
    for ap_out in pn.outputs:
        ap_int = graph.register_ap(ap_out)
        ap_var = buddy.bdd_ithvar(ap_int)
        ap[ap_out] = ap_var
        outputs.add(ap_int)
        spot.set_synthesis_outputs(graph, ap_var)

    #states keeps track of the association marking <=> states of the automatons
    # states = dict() on a plus besoin de ce dictionnaire, on se concentre sur les transitions et non plus sur les marquages

    # chaque etat du controller = cellule du hda
    cell_to_state = dict()

    #edges_ios keeps track of the association edges <=> inputs/outputs
    edges_ios = dict()

    #edges_concsets stores the concset corresponding to each edge
    edges_concsets = dict()

    #states_bdds stores the bdd of inputs/outputs of each state
    states_bdds = dict()

    # on cree directement les etats comme on a deja le hda construit par pn2MAXHDA
    for cell_id, cell in hda.items():
        #on appelle la fonction get_state_for_cell qui creera un nouvel etat du graphe 
        # si necessaire (si pas deja cree, en theorie non) et lui associera la cellule
        get_state_for_cell(cell_id, cell, cell_to_state, graph, pn, ap, states_bdds)

    #on cherche dans le hda la cellule initiale, on prend juste l id car on a deja cree tous les etats correspondant de l hda 
    for cell_id, cell in hda.items():
        if cell.marking == pn.initial and not cell.concset:
            initial_id = cell_id

    initial_state = cell_to_state[initial_id]
    graph.set_init_state(initial_state)

    #on cree les transitions du graphe
    for cell_id, cell in hda.items():
        state = cell_to_state[cell_id]
        #on prend l id de la cellule suivante et les transitions vers elle
        for next_id, hda_edges in cell.transitions.items():
            next_state = cell_to_state[next_id]

            # on parcourt chaque transition (quand on passe d unne cellule a l autre) du hda 
            for hda_edge in hda_edges:
                active = {}
                
                # on lit les transitions actives qui commencent ou terminent
                for t, n in hda_edge.get('start', {}).items():
                    active[t] = n
                for t, n in hda_edge.get('terminate', {}).items():
                    active[t] = n

                # on calcule le bdd output input
                bdd = get_edge_output(active, pn, ap, cell)
                # on rajoute la transition dans le graphe
                edge = graph.new_edge(state, next_state, bdd)
                #on mémorise le concset pour le controller
                edges_concsets[edge] = active
    #for maxcell in hda.keys():
    #    concset = hda[maxcell].concset
    #    marking = compute_marking_pre(hda[maxcell].marking, concset , pn)
    #    add_many_transitions(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking, concset, states)

    return csg(graph, states_bdds, edges_concsets, outputs)

def build_csg_from_files(path_to_pn2hda, pnml_file, io_file):
    """
    Builds the Concurrent Step Graph semantics for the interpreted Petri net specified by the pnml file and the i/o file.
    
    Args:
        path_to_pn2hda: The path to directory containing the pn2HDA and pn2MAXHDA executables. 
        pnml_file: The file containing the Petri net in pnml format.
        io_file: The file specifying the inputs/outputs of the iPN.
    
    Returns:
        The Concurrent Step Graph semantics for the interpreted Petri net specified by the pnml file and the i/o file.
    """
    if path_to_pn2hda is None:
        main_dir = Path(__file__).parent.parent
        matches_pn2HDA = glob.glob(str(main_dir / "*" / "pn2HDA"))
        matches_pn2MAXHDA = glob.glob(str(main_dir / "*" / "pn2MAXHDA"))
    else:
        main_dir = Path(path_to_pn2hda)
        matches_pn2HDA = glob.glob(str(main_dir / "pn2HDA"))
        matches_pn2MAXHDA = glob.glob(str(main_dir / "pn2MAXHDA"))
    if not matches_pn2HDA:
        raise FileNotFoundError("Could not find the C++ executable 'pn2HDA' in pn2HDA/*/")
    pn2HDA = matches_pn2HDA[0]
    pnfetcher = subprocess.run(
    [pn2HDA,"standard", pnml_file, "base"],
    capture_output=True,
    text=True 
    )
    pn_text = pnfetcher.stdout

    if not matches_pn2MAXHDA:
        raise FileNotFoundError("Could not find the C++ executable 'pn2MAXHDA' in pn2HDA/*/")
    pn2MAXHDA = matches_pn2MAXHDA[0]
    hdafetcher = subprocess.run(
    [pn2MAXHDA,"standard", pnml_file, "str"],
    capture_output=True,
    text=True 
    )
    hda_text = hdafetcher.stdout
    
    with open(args.io_file) as io_file:
        pn = parse_petri_net(pn_text)
        hda = parse_maxcell_hda(hda_text, pn)
        ipn = parse_io(pn, io_file.read())
    return hdatocsg(hda, ipn)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
    "--p-path",
    type=str,
    default=None,
    help="Path to the C++ executable p (optional)"
    )
    parser.add_argument("pnml_file", type = str, help="The Petri net file in pnml format")
    parser.add_argument("io_file", type = str, help="The input/output specification file")
    args = parser.parse_args()
    print(build_csg_from_files(args.p_path, args.pnml_file, args.io_file).twa.to_str('hoa'))
        