import spot
import buddy
import argparse
from dataclasses import dataclass

# The controller #
##################

# csg is the class for the controller
class csg:
    def __init__(self, aut, states_bdds, edges_concsets, outputs):
        self.twa = aut
        self.states_bdds = states_bdds
        self.edges_concsets = edges_concsets
        self.outputs = outputs
        self.current_state = 0
    
    # Step makes one transition of the controller: it changes the inner state of the controller following a transition
    # Args: a valuation of AP where the values of input APs are taken for the transition of the controller
    # Return: a valuation of AP where the values of outputs APs are generated by the transition
    def step(self, inputs_val):
        direction_step = self.get_a_paretto_max_edge(inputs_val)
        if direction_step is not None:
            self.current_state = direction_step[1]
            return direction_step[0]
        return compute_outputs(self.states_bdds[self.current_state], self.outputs)

    # Choose an edge taking a Paretto maximal number of inputs in account
    # Return the output generated by the edge and the destination state
    def get_a_paretto_max_edge(self, inputs_val):
        resu_edge = None
        for edge in self.twa.out(self.current_state):
            if satisfies_bdd(inputs_val, edge.cond, self.outputs) and (resu_edge is None or leq_mset(self.edges_concsets[self.twa.edge_number(resu_edge)], self.edges_concsets[self.twa.edge_number(edge)])):
                resu_edge = edge
        if resu_edge is not None:
            return (compute_outputs(resu_edge.cond, self.outputs), resu_edge.dst)
    

# Args: a valuation of the AP, a bdd and outputs APs
# Return: a Boolean indicating whether the valuation satisfies the input part of the bdd
def satisfies_bdd (valuation, bdd, outputs_list):
    if bdd == buddy.bddfalse:
        return False
    if bdd == buddy.bddtrue:
        return True
    top = buddy.bdd_var(bdd)
    low = buddy.bdd_low(bdd)
    high = buddy.bdd_high(bdd)
    if top in outputs_list:
        return satisfies_bdd(valuation, low, outputs_list) or satisfies_bdd(valuation, high, outputs_list)
    if valuation[top]:
        return satisfies_bdd(valuation, high, outputs_list)
    else:
        return satisfies_bdd(valuation, low, outputs_list)

# Args: an automaton, a bdd and outputs APs
# Return: the valuation of output APs according to the bdd
def compute_outputs(bdd, outputs):
    resu = {ap: False for ap in outputs}
    bdd_temp = bdd
    while bdd_temp != buddy.bddtrue:
        top = buddy.bdd_var(bdd_temp)
        low = buddy.bdd_low(bdd_temp)
        high = buddy.bdd_high(bdd_temp)
        if low == buddy.bddfalse:
            if top in outputs:
                resu[top] = True
            bdd_temp = high
            continue
        if high == buddy.bddfalse:
            if top in outputs:
                resu[top] = False
            bdd_temp = low
            continue
        raise Exception("Not a cube!")
    return resu

# Important classes #
#####################

#@dataclass
#class marking:
#    get: tuple

@dataclass
class pnTransition:
    pre: list
    post: list

@dataclass
class petrinet:
    initial: tuple
    map: dict
    transitions: dict

@dataclass
class ipnTransition:
    pre: list
    post: list
    inputs: str
    outputs: str

@dataclass
class ipetrinet:
    initial: tuple
    map: dict
    inputs: list
    outputs: list
    placesOuts: dict
    transitions: dict

@dataclass
class maxCell:
    marking: tuple
    concset: dict
    transitions: dict

@dataclass
class hdaTransition:
    unstrat: dict
    terminate: dict
    continued: dict
    start: dict

# Parsing of input #
####################

# Builds the Petri net specified in pn_text 
def parse_petri_net(pn_text: str): # psc Elargir vers pnml ou le truc de Yan je pense
    Map = dict()
    Transitions = dict()

    lines = pn_text.replace(' ','').split("\n")

    i=0
    while lines[i] != "<Transitions>":
        i += 1
    i0 = i +1
    while lines[i] != "</Transitions>":
        i += 1
    init_marking = tuple([int(m) for m in ((lines[i0-2]).split(":")[1][1:-1]).split(',')]) # psc You could do a eval
    for transition_text in lines[i0:i]:
        parts = transition_text.split(":") # psc you could use a re.match
        name_texts = parts[0].split(",")
        id = int(name_texts[0][1:])
        name = name_texts[1][1:-2]
        Map[id] = name

        defs_places = parts[1].split("],[")
        preplaces = [int(i) for i in defs_places[0][1:].split(",")]
        postplaces = [int(i) for i in defs_places[1][:-1].split(",")]
        Transitions[name] = pnTransition(preplaces, postplaces)
    return petrinet(init_marking, Map, Transitions)

# Builds the interpreted Petri net with base Petri net pn and where the inputs/outputs/ specifications is given by io_text
def parse_io (pn: petrinet, io_text: str):
    lines = io_text.replace(' ', '').split("\n")

    inputs_list = lines[0].split(":")[1][1:-1].split(",")
    outputs_list = lines[1].split(":")[1][1:-1].split(",")
    
    Transitions = dict()

    i=0
    while lines[i] != "<Transitions>":
        i += 1
    i0 = i +1
    while lines[i] != "</Transitions>":
        i += 1
    
    transitions_text = lines[i0:i]
    for transition_text in transitions_text:
        parts = transition_text.split(":")
        name_texts = parts[0].split(",")
        name = name_texts[1][1:-2]
        defs_io = parts[1][1:-1].split(";")
        inputs = defs_io[0]
        outputs = defs_io[1]
        Transitions[name] = ipnTransition(pn.transitions[name].pre,pn.transitions[name].post, inputs, outputs)
    
    placeOuts = dict()
    while lines[i] != "<Place-Output>":
        i += 1
    i0 = i +1
    while lines[i] != "</Place-Output>":
        i += 1
    if i > i0 +1:
        place_out_text = lines[i0:i]
        for placeio_text in place_out_text:
            placeio = placeio_text.split(':')
            outputs = placeio[1][1:-1]
            placeOuts[int(placeio[0])] = outputs
    return ipetrinet(pn.initial, pn.map, inputs_list, outputs_list, placeOuts, Transitions)

def add_transitions(transi_list, pn: ipetrinet, transitions):
    for a in transi_list:
        if a != '':
            char = pn.map[int(a)]
            if char in transitions.keys():
                transitions[char] += 1
            else:
                transitions[char] = 1

# Builds the MaxCell HDA given by hda_text and representing pn
def parse_maxcell_hda(hda_text: str, pn: ipetrinet):
    lines = hda_text.replace(' ','').split("\n")
    Cells = dict()
    i_start = 0
    while i_start<len(lines):
        id = lines[i_start].split(":")
        name = int(id[0])
        markconc = id[1].split("]x[")
        marking = tuple([int(i) for i in markconc[0][1:].split(",")])
        concset = dict()
        for a in markconc[1][:-1].split(","):
            if a in concset.keys():
                concset[a] += 1
            else:
                concset[a] = 1
        Transitions = dict()
        i_end = i_start+2
        while i_end < len(lines) and ":" not in lines[i_end]:
            i_end += 1
        transitions = lines[i_start+2:i_end-1]
        if transitions != []:
            for transition_text in transitions:
                transition_parts = transition_text.split(";")
                maxcell_target = int(transition_parts[3])
                if maxcell_target not in Transitions.keys():
                    Transitions[maxcell_target] = []
                unst_term = transition_parts[1].split("|")

                transition = dict()
                unstart = dict()
                unstart_list = unst_term[0][1:-1].split(",")
                add_transitions(unstart_list, pn, unstart)
                continued = dict()
                continued_list = unst_term[0][1:-1].split(",")
                add_transitions(continued_list, pn, continued)
                terminate = dict()
                terminate_list = unst_term[1][1:-1].split(",")
                add_transitions(terminate_list, pn, terminate)
                start = dict() #psc I would again suggest a re.match
                start_list = transition_parts[2].split("|")[1][1:-1].split(",")
                add_transitions(start_list, pn, start)
                Transitions[maxcell_target].append(transition)
        Cells[name] = maxCell(marking, concset, Transitions)
        i_start = i_end
    return Cells

# Computing concurrent step graph #
###################################

# MultiSet operations #
# ------------------- #

# Compute the complementary multiset of mset in bigmset
def compute_comp_mset(mset, bigmset):
    return diff_mset(bigmset, mset)

# Compute the difference mset1 - mset2
def diff_mset(mset1, mset2):
    resu = dict()
    for key in mset1.keys() & mset2.keys():
        value = mset1[key] - mset2[key]
        if value > 0:
            resu[key] = value
    for key in set(mset1.keys()).difference(mset2.keys()):
        resu[key] = mset1[key]
    return resu

# Predicate whether mset1 <= mset2
def leq_mset(mset1, mset2):
    for key in mset1.keys(): # psc compute intersection beforehand
        if key not in mset2.keys() or mset1[key] > mset2[key]:
            return False
    return True

# Predicate whether there is mset2 in msets such that mset2 <= mset1 (a smaller version of mset is already in msets)
def is_subsumed_msets(mset, msets):
    return any (leq_mset(mset2, mset) for mset2 in msets)

# Generate all sub-multisets of mset for the keys keys 
# psc Does this generate duplicates and if so is that a problem?
# psc Wrapper function?
def sub_multi_set(mset, keys):
    if len(keys) == 0:
        yield dict()
    else:
        key = keys.pop()
        for sub_mset in sub_multi_set(mset, keys):
            for i in range(mset[key]+1):
                if i != 0:
                    sub_mset[key] = i
                elif key in sub_mset.keys():
                    del sub_mset[key]
                yield sub_mset.copy()
        keys.add(key)

# Operations on markings of the Petri-net #
# --------------------------------------- #

# Compute the new marking obtained after unstarting all transitions in concset from marking in pn 
# psc Use np.array
# psc I feel like the three should somehow be factored
def compute_marking_pre(marking, concset, pn):
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for transition in concset.keys():
            if place in pn.transitions[transition].pre:
                mplace += concset[transition]
        new_marking = new_marking + (mplace,) # psc this is not ideal performance wise
    return new_marking


# Compute the new marking obtained after firing and terminating all transitions in concset from marking in pn 
def compute_marking_transi(marking, concset, pn: ipetrinet):
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for transition in concset.keys():
            if place in pn.transitions[transition].pre:
                mplace -= concset[transition]
                if mplace < 0:
                    raise Exception("transition with not enough tokens")
            if place in pn.transitions[transition].post:
                mplace += concset[transition]
        new_marking = new_marking + (mplace,)
    return new_marking

# Compute the new marking obtained after applying the MaxCell transitions (in the MaxCell HDA) 
def compute_marking_maxcell_transi(marking, transitions: hdaTransition, pn: ipetrinet):
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for unstart in transitions.unstart.keys():
            if place in pn.transitions[unstart].pre:
                mplace += transitions.unstart[unstart]
        for terminate in transitions.terminate.keys():
            if place in pn.transitions[terminate].post:
                mplace += transitions.terminate[terminate]
        for start in transitions.start.keys():
            if place in pn.transitions[start].pre:
                mplace -= transitions.start[start]
                if mplace < 0:
                    raise Exception("transition with not enough tokens")
        new_marking = new_marking + (mplace,)
    return new_marking

# Logcal operations #
# ----------------- #

# Get the ap of a literal
def get_literal(strg, ap):
    if strg[0] == "!":
        return buddy.bdd_not(ap[strg[1:]])
    else:
        return ap[strg]

# Gives a copy of the input string without spaces
def remove_space(strg):
    resu = "" # psc str.replace(" ","")
    for char in strg:
        if char !=' ':
            resu = resu + char
    return resu

# Builds a bdd for the string strg over APs ap
# psc I'm confused, what is the input? SOP?
def get_string_bdd(strg, ap):
    clauses = remove_space(strg).split('&')
    resu = buddy.bddtrue
    for clause in clauses:
        literals = clause.split('|')
        resu_clause = buddy.bddfalse
        for literal in literals:
            resu_clause = resu_clause | get_literal(literal, ap)
        resu = resu & resu_clause
    return resu

# Builds the bdd for the output of a marking
def get_marking_output(marking, pn: ipetrinet, ap):
    resu = buddy.bddtrue
    for state in range(len(marking)):
        if state in pn.placesOuts.keys() and marking[state] > 0:
            resu = resu & get_string_bdd(pn.placesOuts[state], ap) # psc normally try except should be faster
    return resu

# Build a new state in our automaton
def get_state(marking, states, graph, pn, ap, states_bdds):
    if marking in states:
        state = states[marking]
    else:
        label = get_marking_output(marking, pn, ap)
        state = graph.new_state()
        states[marking] = state
        states_bdds[state] = label
    return state

# If a bdd for the inputs of a transition is false, the transition is not added to the automaton
class Inputs_Error (Exception):
    pass

# If a bdd for the outputs is false, then, this error is raised
class Outputs_Error (Exception):
    def __init__(self, message):            
        super().__init__(message)

# returns the input/output bdd when firing concset from marking_source
def get_io(marking_source, concset, pn, ap):
    resu = get_marking_output(marking_source, pn, ap)
    for t in concset.keys():
        inputs = pn.transitions[t].inputs
        outputs = pn.transitions[t].outputs
        if inputs:
            bdd_inputs = get_string_bdd(inputs, ap)
            resu = resu & bdd_inputs
            if resu == buddy.bddfalse:
                raise Inputs_Error
        if outputs:
            bdd_outputs = get_string_bdd(outputs, ap)
            resu = resu & bdd_outputs
            if resu == buddy.bddfalse:
                raise Outputs_Error(f"Incompatible outputs in {marking_source} when firing {concset}")
            resu = resu & get_string_bdd(outputs, ap)
    return resu

# Adds a transition in the automaton from the state representing marking_source and following concset. Returns the obtained marking
def add_transition(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking_source, concset, states):
    marking_target = compute_marking_transi(marking_source, concset, pn)
    state_source = get_state(marking_source, states, graph, pn, ap, states_bdds)
    state_target = get_state(marking_target, states, graph, pn, ap, states_bdds)
    try:
        label = get_io(marking_source, concset, pn, ap)
    except Inputs_Error:
        return marking_target
    if not (marking_source, marking_target) in edges_ios.keys():
        edge = graph.new_edge(state_source, state_target, label)
        edges_concsets[edge] = concset
        edges_ios[(marking_source, marking_target)] = [label]
    elif not any(existing_label == label for existing_label in edges_ios[(marking_source, marking_target)]):
        edge = graph.new_edge(state_source, state_target, label)
        edges_concsets[graph.edge_number(edge)] = concset
        edges_ios[(marking_source, marking_target)].append(label)
    return marking_target

# Adds all the transitions from marking_source in the current cell with concset {concset}
def add_many_transitions(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking_source, concset, states):
    set_keys = set(concset.keys())
    for mset in sub_multi_set(concset, set_keys):
        if len(mset) != 0:
            marking_target = add_transition(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking_source, mset, states)
            concset_comp = compute_comp_mset(mset, concset)
            add_many_transitions(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking_target, concset_comp, states)

# Takes an HDA in MAXCELL form that represents the petri net pn in inputs and produces its concurentstep graph associated
def hdatocsg (hda, pn: ipetrinet):
    bdict = spot.make_bdd_dict()
    graph = spot.make_twa_graph(bdict)

    ap = dict()
    for ap_in in pn.inputs:
        ap_var = buddy.bdd_ithvar(graph.register_ap(ap_in))
        ap[ap_in] = ap_var
    
    outputs = set()
    for ap_out in pn.outputs:
        ap_int = graph.register_ap(ap_out)
        ap_var = buddy.bdd_ithvar(ap_int)
        ap[ap_out] = ap_var
        outputs.add(ap_int)
        spot.set_synthesis_outputs(graph, ap_var)

    #states keeps track of the association marking <=> states of the automatons
    states = dict()

    #edges_ios keeps track of the association edges <=> inputs/outputs
    edges_ios = dict()

    #edges_concsets stores the concset corresponding to each edge
    edges_concsets = dict()

    #states_bdds stores the bdd of inputs/outputs of each state
    states_bdds = dict()

    initial_state = get_state(pn.initial, states, graph, pn, ap, states_bdds)
    graph.set_init_state(initial_state)
    for maxcell in hda.keys():
        concset = hda[maxcell].concset
        marking = compute_marking_pre(hda[maxcell].marking, concset , pn)
        add_many_transitions(graph, pn, ap, states_bdds, edges_ios, edges_concsets, marking, concset, states)
    return csg(graph, states_bdds, edges_concsets, outputs)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("hda_file")
    parser.add_argument("pn_file")
    parser.add_argument("io_file")
    args = parser.parse_args()
    with open(args.hda_file) as hda_file, open(args.pn_file) as pn_file, open(args.io_file) as io_file:
        pn = parse_petri_net(pn_file.read())
        ipn = parse_io(pn, io_file.read())
        hda = parse_maxcell_hda(hda_file.read(), ipn)
        graph = hdatocsg(hda, ipn)
        print(graph.twa.to_str('hoa'))
        