import spot
import buddy
import argparse

# The controller #
##################

# My_twa is the class for the controller
class my_twa:
    def __init__(self, aut, states_labels, outputs):
        self.twa = aut
        self.outputs = outputs
        self.states_labels = states_labels
        self.current_state = 0
    
    # Step makes one transition of the controller: it changes the inner state of the controller following a transition
    # Args: a valuation of AP where the values of input APs are taken for the transition of the controller
    # Return: a valuation of AP where the values of outputs APs are generated by the transition
    def step(self, inputs):
        for edge in self.twa.out(self.current_state):
            if satisfies_bdd(inputs, edge.cond, self.outputs):
                self.current_state = edge.dst
                return compute_outputs(self.twa, edge.cond, self.outputs)
        return compute_outputs(self.twa, self.states_labels[self.current_state], self.outputs)

# Args: a valuation of the AP, a bdd and outputs APs
# Return: a Boolean indicating whether the valuation satisfies the input part of the bdd
def satisfies_bdd (valuation, bdd, outputs):
    if bdd == buddy.bddfalse:
        return False
    if bdd == buddy.bddtrue:
        return True
    top = buddy.bdd_var(bdd)
    low = buddy.bdd_low(bdd)
    high = buddy.bdd_high(bdd)
    if top in outputs:
        return satisfies_bdd(valuation, low, outputs) or satisfies_bdd(valuation, high, outputs)
    if valuation[top]:
        return satisfies_bdd(valuation, high, outputs)
    else:
        return satisfies_bdd(valuation, low, outputs)

# Args: an automaton, a bdd and outputs APs
# Return: the valuation of output APs according to the bdd     # psc this is the same as outputs[var]

def compute_outputs(aut, bdd, outputs):
    resu = [False]*len(aut.ap()) # psc this is very dangerous; You assume there are no other variables 
    bdd_temp = bdd
    while bdd_temp != buddy.bddtrue:
        top = buddy.bdd_var(bdd_temp)
        low = buddy.bdd_low(bdd_temp)
        high = buddy.bdd_high(bdd_temp)
        if low == buddy.bddfalse:
            if top in outputs:
                resu[top] = True
            bdd_temp = high
            continue
        if high == buddy.bddfalse:
            bdd_temp = low
            continue
        raise Exception("Not a cube!")
    return resu

# Parsing of input #
####################

# Builds a dictionary representing the Petri net specified in pn_text 
def parse_petri_net(pn_text): # psc I'm confused: do we not use pnml?
    pn = dict()
    pn["Map"] = dict()
    pn["Transitions"] = dict()

    lines = pn_text.split("\n")

    i=0
    while lines[i] != "<Transitions>":
        i += 1
    i0 = i +1
    while lines[i] != "</Transitions>":
        i += 1
    init_marking = tuple([int(m) for m in ((lines[i0-2]).split(": ")[1][1:-1]).split(',')]) # psc You could do a eval
    pn["Initial"] = init_marking
    transitions_text = lines[i0:i] # psc I fear this makes a hard copy
    for transition_text in transitions_text:
        parts = transition_text.split(": ") # psc you could use a re.match
        name_texts = parts[0].split(",")
        id = int(name_texts[0][1:])
        name = name_texts[1][1:-2]
        pn["Map"][id] = name
        pn["Transitions"][name] = dict()
        defs_places = parts[1].split("],[")
        preplaces = [int(i) for i in defs_places[0][1:].split(",")]
        postplaces = [int(i) for i in defs_places[1][:-1].split(",")]
        pn["Transitions"][name]["pre"] = preplaces
        pn["Transitions"][name]["post"] = postplaces
    return pn

# Adds to pn the inputs/outputs/ specifications given in io_text
def parse_io (pn, io_text):
    lines = io_text.split("\n")

    pn["Inputs"] = lines[0].split(": ")[1][1:-1].split(",") # psc beware of spaces
    pn["Outputs"] = lines[1].split(": ")[1][1:-1].split(",")
    
    i=0
    while lines[i] != "<Transitions>":
        i += 1
    i0 = i +1
    while lines[i] != "</Transitions>":
        i += 1
    
    transitions_text = lines[i0:i]
    for transition_text in transitions_text:
        parts = transition_text.split(": ")
        name_texts = parts[0].split(",")
        name = name_texts[1][1:-2]
        defs_io = parts[1][1:-1].split(";")
        inputs = defs_io[0]
        outputs = defs_io[1]
        pn["Transitions"][name]["inputs"] = inputs
        pn["Transitions"][name]["outputs"] = outputs
    
    pn["PlaceIO"] = dict()
    while lines[i] != "<Place-Output>":
        i += 1
    i0 = i +1
    while lines[i] != "</Place-Output>":
        i += 1
    if i > i0 +1:
        place_out_text = lines[i0:i]
        for placeio_text in place_out_text:
            placeio = placeio_text.split(':')
            outputs = placeio[1][1:-1]
            pn["PlaceIO"][int(placeio[0])] = outputs

# Builds the dictionnary representing the MaxCell HDA given by hda_text and representing pn
def parse_maxcell_hda(hda_text, pn):
    lines = hda_text.split("\n")
    hda = dict()
    i_start = 0
    while i_start<len(lines):
        id = lines[i_start].split(" : ")
        name = int(id[0])
        hda[name] = dict()
        markconc = id[1].split(" x ")
        marking = tuple([int(i) for i in markconc[0][1:-1].split(",")])
        concset = dict()
        for a in markconc[1][1:-1].split(","):
            if a in concset.keys():
                concset[a] += 1
            else:
                concset[a] = 1
        hda[name]["Marking"] = marking # psc I suggest making HDA a dataclass
        hda[name]["Concset"] = concset
        hda[name]["Transitions"] = dict()

        i_end = i_start+2
        while i_end < len(lines) and ":" not in lines[i_end]:
            i_end += 1
        transitions = lines[i_start+2:i_end-1]
        if transitions != []:
            for transition_text in transitions:
                transition_parts = transition_text.split(";")
                maxcell_target = int(transition_parts[3])
                if maxcell_target not in hda[name]["Transitions"].keys():
                    hda[name]["Transitions"][maxcell_target] = []
                transition = dict()
                transition["Unstart"] = dict()
                transition["Terminate"] = dict()
                transition["Continued"] = dict()
                transition["Start"] = dict()
                unst_term = transition_parts[1].split("|") #psc I would again suggest a re.match
                unstart_list = unst_term[0][1:-1].split(",")
                continued_list = unst_term[0][1:-1].split(",")
                terminate_list = unst_term[1][1:-1].split(",")
                start_list = transition_parts[2].split("|")[1][1:-1].split(",")
                for a in unstart_list:
                    if a != '':
                        char = pn["Map"][int(a)]
                        if char in transition["Unstart"].keys():
                            transition["Unstart"][char] += 1
                        else:
                            transition["Unstart"][char] = 1
                for a in terminate_list:
                    if a != '':
                        char = pn["Map"][int(a)]
                        if char in transition["Terminate"].keys():
                            transition["Terminate"][char] += 1
                        else:
                            transition["Terminate"][char] = 1
                for a in continued_list:
                    if a != '':
                        char = pn["Map"][int(a)]
                        if char in transition["Continued"].keys():
                            transition["Continued"][char] += 1
                        else:
                            transition["Continued"][char] = 1
                for a in start_list:
                    if a != '':
                        char = pn["Map"][int(a)]
                        if char in transition["Start"].keys():
                            transition["Start"][char] += 1
                        else:
                            transition["Start"][char] = 1
                hda[name]["Transitions"][maxcell_target].append(transition)
        i_start = i_end
    return hda

# Computing concurrent step graph #
###################################

# MultiSet operations #
# ------------------- #

# Compute the complementary multiset of mset in bigmset
def compute_comp_mset(mset, bigmset):
    resu = dict()
    for key in bigmset.keys(): # psc compute intersection beforehand
        if key in mset.keys():
            if mset[key] < bigmset[key]:
                resu[key] = bigmset[key] - mset[key]
        else:
            resu[key] = bigmset[key]
    return resu

# Compute the difference mset1 - mset2
def diff_mset(mset1, mset2):
    resu = dict()
    for key in mset1.keys(): # psc compute intersection beforehand
        if key in mset2.keys():
            value = mset1[key] - mset2[key]
            if value > 0:
                resu[key] = value
        else:
            resu[key] = mset1[key]
    return resu

# Predicate whether mset1 <= mset2
def leq_mset(mset1, mset2):
    for key in mset1.keys():
        if key not in mset2.keys() or mset1[key] > mset2[key]:
            return False
    return True

# Predicate whether there is mset2 in msets such that mset2 <= mset1 (a smaller version of mset is already in msets)
def is_subsumed_msets(mset, msets):
    for mset2 in msets:
        if leq_mset(mset2, mset):
            return True
    return False

# Generate all sub-multisets of mset for the keys keys 
def sub_multi_set(mset, keys):
    if len(keys) == 0:
        yield dict()
    else:
        key = keys.pop()
        for sub_mset in sub_multi_set(mset, keys):
            for i in range(mset[key]+1):
                if i != 0:
                    sub_mset[key] = i
                elif key in sub_mset.keys():
                    del sub_mset[key]
                yield sub_mset.copy()
        keys.add(key)

# Operations on markings of the Petri-net #
# --------------------------------------- #

# Compute the new marking obtained after unstarting all transitions in concset from marking in pn 
def compute_marking_pre(marking, concset, pn) :
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for transition in concset.keys():
            if place in pn["Transitions"][transition]["pre"] :
                mplace += concset[transition]
        new_marking = new_marking + (mplace,)
    return new_marking


# Compute the new marking obtained after firing and terminating all transitions in concset from marking in pn 
def compute_marking_transi(marking, concset, pn) :
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for transition in concset.keys():
            if place in pn["Transitions"][transition]["pre"] :
                mplace -= concset[transition]
                if mplace < 0:
                    raise Exception("transition with not enough tokens")
            if place in pn["Transitions"][transition]["post"] :
                mplace += concset[transition]
        new_marking = new_marking + (mplace,)
    return new_marking

# Compute the new marking obtained after applying the MaxCell transitions (in the MaxCell HDA) 
def compute_marking_maxcell_transi(marking, transitions, pn) :
    new_marking = ()
    for place in range(len(marking)):
        mplace = marking[place]
        for unstart in transitions["Unstart"].keys():
            if place in pn["Transitions"][unstart]["pre"] :
                mplace += transitions["Unstart"][unstart]
        for terminate in transitions["Terminate"].keys():
            if place in pn["Transitions"][terminate]["post"] :
                mplace += transitions["Terminate"][terminate]
        for start in transitions["Start"].keys():
            if place in pn["Transitions"][start]["pre"] :
                mplace -= transitions["Start"][start]
                if mplace < 0:
                    raise Exception("transition with not enough tokens")
        new_marking = new_marking + (mplace,)
    return new_marking

# Predicate whether a face with concset {concset} is entierly included in an cell adjacent to the current one and thus, can be skipped.
def has_face_covered(concset, transitions_list):
    set_keys = set(concset.keys())
    for subconcset in sub_multi_set(concset, set_keys):
        if not any(subconcset == transition["Continued"] for transition in transitions_list):
            return False
    return True

# Compute the list of marking that can be exempted of recursive call
def compute_markings_avoidable(marking, transitions_dict, pn):
    resu = []
    for maxcell in transitions_dict:
        for transitions in transitions_dict[maxcell]:
            if has_face_covered(transitions["Continued"], transitions_dict[maxcell]):
                resu.append(compute_marking_maxcell_transi(marking, transitions, pn))
    return resu

# Logcal operations #
# ----------------- #

# Get the ap of a literal
def get_literal(strg, ap):
    if strg[0] == "!":
        return buddy.bdd_not(ap[strg[1:]])
    else:
        return ap[strg]

# Gives a copy of the input string without spaces
def remove_space(strg):
    resu = ""
    for char in strg:
        if char !=' ':
            resu = resu + char
    return resu

# Builds a bdd for the string strg over APs ap
def get_string_bdd(strg, ap):
    clauses = remove_space(strg).split('&')
    resu = buddy.bddtrue
    for clause in clauses:
        literals = clause.split('|')
        resu_clause = buddy.bddfalse
        for literal in literals:
            resu_clause = resu_clause | get_literal(literal, ap)
        resu = resu & resu_clause
    return resu

# Builds the bdd for the output of a marking
def get_marking_output(marking, pn, ap):
    resu = buddy.bddtrue
    for state in range(len(marking)):
        if state in pn["PlaceIO"].keys() and marking[state] > 0:
            resu = resu & get_string_bdd(pn["PlaceIO"][state], ap)
    return resu

# Build a new state in our automaton
def get_state(marking, states, csg, pn, ap, states_label):
    if marking in states:
        state = states[marking]
    else:
        label = get_marking_output(marking, pn, ap)
        state = csg.new_state()
        states[marking] = state
        states_label[state] = label
    return state

# If a bdd for the inputs of a transition is false, the transition is not added to the automaton
class Inputs_Error (Exception):
    pass

# If a bdd for the outputs is false, then, this error is raised
class Outputs_Error (Exception):
    def __init__(self, message):            
        super().__init__(message)

# returns the input/output bdd when firing concset from marking_source
def get_io(marking_source, concset, pn, ap):
    resu = get_marking_output(marking_source, pn, ap)
    for t in concset.keys():
        inputs = pn["Transitions"][t]["inputs"]
        outputs = pn["Transitions"][t]["outputs"]
        if inputs:
            bdd_inputs = get_string_bdd(inputs, ap)
            resu = resu & bdd_inputs
            if resu == buddy.bddfalse:
                raise Inputs_Error
        if outputs:
            bdd_outputs = get_string_bdd(outputs, ap)
            resu = resu & bdd_outputs
            if resu == buddy.bddfalse:
                raise Outputs_Error(f"Incompatible outputs in {marking_source} when firing {concset}")
            resu = resu & get_string_bdd(outputs, ap)
    return resu

# Adds a transition in the automaton from the state representing marking_source and following concset. Returns the obtained marking
def add_transition(csg, pn, ap, states_label, edges_labels, marking_source, concset, states):
    marking_target = compute_marking_transi(marking_source, concset, pn)
    state_source = get_state(marking_source, states, csg, pn, ap, states_label)
    state_target = get_state(marking_target, states, csg, pn, ap, states_label)
    try:
        label = get_io(marking_source, concset, pn, ap)
    except Inputs_Error:
        return marking_target
    if not (marking_source, marking_target) in edges_labels.keys():
        edge = csg.new_edge(state_source, state_target, label)
        edges_labels[(marking_source, marking_target)] = [label]
    elif not any(existing_label == label for existing_label in edges_labels[(marking_source, marking_target)]):
        edge = csg.new_edge(state_source, state_target, label)
        edges_labels[(marking_source, marking_target)].append(label)
    return marking_target

# Adds all the transitions from marking_source in the current cell with concset {concset}
def add_many_transitions(csg, pn, ap, states_label, edges_labels, marking_source, concset, states, markings_avoidable):
    set_keys = set(concset.keys())
    for mset in sub_multi_set(concset, set_keys):
        if len(mset) != 0:
            marking_target = add_transition(csg, pn, ap, states_label, edges_labels, marking_source, mset, states)
            concset_comp = compute_comp_mset(mset, concset)
            if not marking_target in markings_avoidable:
                markings_avoidable.append(marking_target)
                add_many_transitions(csg, pn, ap, states_label, edges_labels, marking_target, concset_comp, states, markings_avoidable)

# Takes an HDA in MAXCELL form that represents the petri net pn in inputs and produces its concurentstep graph associated
def hdatocsg (hda, pn) :
    bdict = spot.make_bdd_dict()
    csg = spot.make_twa_graph(bdict)

    ap = dict()
    for ap_in in pn["Inputs"]:
        ap_var = buddy.bdd_ithvar(csg.register_ap(ap_in))
        ap[ap_in] = ap_var
    
    outputs = set()
    for ap_out in pn["Outputs"]:
        ap_int = csg.register_ap(ap_out)
        ap_var = buddy.bdd_ithvar(ap_int)
        ap[ap_out] = ap_var
        outputs.add(ap_int)
        spot.set_synthesis_outputs(csg, ap_var)

    #states keeps track of the association marking <=> states of the automatons
    states = dict()

    edges_labels = dict()
    states_label = dict()

    initial_state = get_state(pn["Initial"], states, csg, pn, ap, states_label)
    csg.set_init_state(initial_state)
    for maxcell in hda.keys() :
        concset = hda[maxcell]["Concset"]
        marking = compute_marking_pre(hda[maxcell]["Marking"], concset , pn)
        markings_avoidable = compute_markings_avoidable(marking, hda[maxcell]["Transitions"], pn)
        add_many_transitions(csg, pn, ap, states_label, edges_labels, marking, concset, states, markings_avoidable)
    return my_twa(csg, states_label, outputs)

if __name__ == "__main__" :
    parser = argparse.ArgumentParser()
    parser.add_argument("hda_file")
    parser.add_argument("pn_file")
    parser.add_argument("io_file")
    args = parser.parse_args()
    with open(args.hda_file) as hda_file, open(args.pn_file) as pn_file, open(args.io_file) as io_file:
        pn = parse_petri_net(pn_file.read())
        parse_io(pn, io_file.read())
        hda = parse_maxcell_hda(hda_file.read(), pn)
        csg = hdatocsg(hda, pn)
        print(csg.twa.to_str('hoa'))
        